broadcast_rankup: true

player-data:
  storage: sqlite
  save-interval: 300
  SQLite:
    tablename: Rankpoint
    file: './plugins/Rankpoint/SQLite.db'
  MySQL:
    hostname: localhost
    port: 3306
    database: minecraft
    tablename: Rankpoint
    parameters: '?useSSL=false'
    username: root
    password: password

# 아래는 설정 예시
groups:
  1:
    group: Newbie
    point: 0 # 맨 처음 접속했을때 설정되는 그룹
  2:
    group: User
    point: 50 # Newbie 그룹에서 50포인트 획득시 User 로 진급
  3:
    group: VIP1
    point: 100 # -
  4:
    group: VIP2
    point: 200 # VIP1 그룹에서 200 포인트 획득 시 VIP2 로 진급 (VIP2에서부터는 무슨숫자든 진급 X)