player-data:
  storage: sqlite
  save-interval: 300
  SQLite:
    tablename: Rankpoint
    file: './plugins/Rankpoint/SQLite.db'
  MySQL:
    hostname: localhost
    port: 3306
    database: minecraft
    tablename: Rankpoint
    parameters: '?useSSL=false'
    username: root
    password: password

# 아래는 설정 예시
groups:
  1:
    group: Newbie
    point: 10 # 포인트 0부터 10까지는 Newbie
  2:
    group: User
    point: 50 # 포인트 11부터 50까지는 User
  3:
    group: VIP1
    point: 100 # -
  4:
    group: VIP2
    point: -1 # 101 부터 VIP2 (마지막은 무슨숫자든 제한 X)