name: Rankpoint
version: @version@
main: net.utory.rankpoint.Rankpoint
api-version: 1.16
website: www.teamuni.net
author: UTORY
depend: [Vault]

commands:
  rankpoint:
    aliases: [rp, rpoint, rpoints, rankpoints]
    permission: rankpoint.use

permissions:
  rankpoint.*:
    children:
      rankpoint.use: true
      rankpoint.admin: true
  rankpoint.use:
    default: true
  rankpoint.admin:
    default: op